# Build stage
FROM --platform=linux/amd64 rust:1.89-slim as builder

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev && \
    rm -rf /var/lib/apt/lists/*

RUN cargo build --release

# Runtime stage
FROM --platform=linux/amd64 debian:bookworm-slim

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

RUN apt-get update \
    && apt-get install -y wget gnupg ca-certificates \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd -r app && useradd -rm -g app -G audio,video app

RUN which google-chrome-stable

USER app
WORKDIR /home/app

COPY --from=builder --chown=app:app /app/target/release/html-to-pdf-rust .

ENV CHROME_PATH=/usr/bin/google-chrome-stable
ENV PORT=5000

EXPOSE 5000

CMD ["./html-to-pdf-rust"]